### ISSUE TITLE
Can't execute pub global run scaff successfully

### ISSUE THREAD

**Issue by AdMeen89** [ganeshrvel/pub-scaff#1]
When I try to run `pub global run scaff` every time I get an error:

```
Unhandled exception:
StdinException: Error getting terminal echo mode, OS Error: Inappropriate ioctl for device, errno = 25
#0      Stdin.echoMode (dart:io-patch/stdio_patch.dart:71:7)
#1      get (package:prompts/prompts.dart:60:27)
#2      CliParser.getCliStream (package:scaff/src/classes/cli_parser.dart:51:23)
#3      main (file:///Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/scaff-1.2.0+2/lib/src/main.dart:22:31)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

What should I do for avoiding this problem?

Scaff version: 1.2.0+2
OS: BigSur 11.2.1 (20D74)

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

The folder structure is exactly the same as in your example.
Full regards.

**Comment by ganeshrvel** [comment]
I never had this issue. I will check.

**Comment by mohachouch** [comment]
I have the same error, on Windows.

Full Regards

**Comment by ganeshrvel** [comment]
What flutter version are you guys on?

**Comment by mohachouch** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [version 10.0.18363.1379], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

Thanks for your help

**Comment by AdMeen89** [comment]
> What flutter version are you guys on?

As I've written above:

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by mohachouch** [comment]
Hello @ganeshrvel 

Any news for this issue,

Thanks for your work

**Comment by ganeshrvel** [comment]
@mohachouch unfortunately I am not getting time. I shall look into this issue this weekend and will update this thread.

**Comment by ganeshrvel** [comment]
Could you check if the below commands fixes your problem?

```shell
 $ pub global activate scaff 1.2.0+2
 $ pub global run scaff 1.2.0+2     
```


@mohachouch @AdMeen89

**Comment by mohachouch** [comment]
Hi @ganeshrvel 

I tried the solution, unfortunately it doesn't work.

I have the same error.

Thanks for your help
